name = "sundae/freezer"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'sundae/freezer'"

[repository]
user = "sundae"
project = "freezer"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "main"
source = "github"
