name = "SundaeSwap-finance/freezer"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for Sundae Yield Farming"

[repository]
user = "SundaeSwap-finance"
project = "freezer"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.2.0"
source = "github"

[[dependencies]]
name = "SundaeSwap-finance/aicone"
version = "main"
source = "github"