name: Tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  freezer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contracts/freezer
    steps:
      - uses: actions/checkout@v3

      - uses: aiken-lang/setup-aiken@v0.1.0
        with:
          version: v1.0.7-alpha

      - run: aiken fmt --check
      - run: aiken check
      # - run: aiken build

  modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - run: go test ./...
