name: Tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  freezer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contracts/freezer
    steps:
      - uses: actions/checkout@v3

      - uses: aiken-lang/setup-aiken@v0.1.0
        with:
          version: v1.0.7-alpha

      - run: aiken fmt --check
      - run: aiken check
      - run: aiken build
